language: node_js
node_js:
  - "lts/carbon"
cache:
  directories:
    - node_modules
script:
  - npm run build --production
  - npm run coverage
after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
after_success:
  - ./node_modules/.bin/lhci autorun --upload.target=temporary-public-storage
  - npm run bundlesize

deploy:
  provider: s3
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: quintin-donnelly.com
  skip_cleanup: true
  acl: public_read
  local_dir: build
  on:
    branch: master