language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run coverage
  - npm run build
after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
after_success:
  - chmod +x ./scripts/publish.sh
  - ./scripts/publish.sh