language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run coverage
  - npm run build --production
after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
after_success:
  - npm run lh -- https://deploy-preview-$TRAVIS_PULL_REQUEST-blissful-noether-dca508.netlify.com/
  - npm run bundlesize

deploy:
  provider: s3
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: quintin-donnelly.com
  skip_cleanup: true
  acl: public_read
  local_dir: build
  on:
    branch: master