version: 0.2

phases:
  install:
    commands:
      - apt-get -y update
      - apt-get -y install google-chrome-stable
      - npm install
  build:
    commands:
      - npm run build --production
      - npm run coverage
      - echo $CODEBUILD_WEBHOOK_EVENT
  post_build:
    commands:
      - echo Build completed on `date`
      - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
      - ./node_modules/.bin/lhci autorun
      - npm run bundlesize