version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build --production
      - npm run coverage
      - echo $CODEBUILD_WEBHOOK_EVENT
  post_build:
    commands:
      - echo Build completed on `date`
      - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls